# Generated by Django 4.1.3 on 2022-11-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("to_do", models.CharField(default="", max_length=100)),
                ("description", models.CharField(default="", max_length=1000)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                ("status", models.BooleanField(default=False)),
            ],
        ),
    ]
