# Generated by Django 4.1.3 on 2022-11-18 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo", old_name="status", new_name="todo_status",
        ),
    ]
